version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT}:2345
    volumes:
      - .:/clean_web
    env_file: .env
    container_name: boilerplate-web
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: boilerplate-db
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - 33066:3306
    volumes:
      - boilerplate_db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  boilerplate_db:
